trigger:

- main
- feature/*

resources:
  repositories:
    - repository: Infrastructure
      type: git
      name: Webs/Infrastructure

variables:
  - name: appToken
    value: $(token)
  - name: npmToken
    value: $(NPM_TOKEN)
  - name: accountName
    value: $(ACCOUNT_NAME)
  - name: accountKey
    value: $(ACCOUNT_KEY)
  - name: containerName
    value: $(CONTAINER_NAME)

stages:
  - stage: RunTest
    displayName: Run tests
    pool:
      name: Ubuntu WSL
    jobs:
    - job: Test
      steps:
      - checkout: self
        clean: false
        submodules: true
      - task: Yarn@3
        displayName: Install Packages
        inputs:
          projectDirectory: "$(Build.SourcesDirectory)"
          arguments: 'install --frozen-lockfile'
      - task: Yarn@3
        displayName: Run test
        inputs:
          projectDirectory: "$(Build.SourcesDirectory)"
          arguments: test
  - stage: SetVariables
    displayName: Set publish variables
    dependsOn: RunTest
    pool:
      name: Ubuntu WSL
    jobs:
    - job: SetVariables
      steps:
        - checkout: self
        - checkout: Infrastructure
        - task: Bash@3
          displayName: Check package version
          inputs:
            filePath: "$(Build.SourcesDirectory)/Infrastructure/scripts/check-npm-version.sh"
            arguments: "@djeka07/ui"
            workingDirectory: "$(Build.SourcesDirectory)/ui"
          name: OutputVar
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              # Write your commands here
              echo "variables: $(OutputVar.SHOULD_PUBLISH) $(OutputVar.IS_RC) $(OutputVar.PACKAGE_VERSION)"
  - stage: Publish
    displayName: Publish to NPM
    dependsOn: SetVariables
    condition: eq(dependencies.SetVariables.outputs['SetVariables.OutputVar.SHOULD_PUBLISH'], true)
    pool:
      name: Ubuntu WSL
    jobs:
      - job: Publish
        variables:
          isRc: $[stageDependencies.SetVariables.SetVariables.outputs['OutputVar.IS_RC']]
          packageVersion:  $[stageDependencies.SetVariables.SetVariables.outputs['OutputVar.PACKAGE_VERSION']]
        steps:
          - checkout: self
          - checkout: Infrastructure
          - task: Yarn@3
            displayName: Install Packages
            inputs:
              projectDirectory: "$(Build.SourcesDirectory)/ui"
              arguments: 'install --frozen-lockfile'
          - task: Bash@3
            displayName: 'Publish package to NPM'
            inputs:
              filePath: "$(Build.SourcesDirectory)/Infrastructure/scripts/publish.sh"
              arguments: "$(isRc) $(npmToken)"
              workingDirectory: "$(Build.SourcesDirectory)/ui"
          - task: AzureCLI@2
            name: useDynamicInstall
            displayName: Use dynamic install
            inputs:
              azureSubscription: 'PremiumConnection'
              scriptType: 'bash'
              scriptLocation: inlineScript
              inlineScript: 'az config set extension.use_dynamic_install=yes_without_prompt'
              visibleAzLogin: false
          - task: AzureCLI@2
            name: UploadBlobs
            displayName: Upload style.css to blob storage
            inputs:
              azureSubscription: 'PremiumConnection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: 'az storage fs directory upload --source $(Build.SourcesDirectory)/ui/dist/style.css -d /$(packageVersion)/style.css -f $(containerName) --account-name $(accountName) --account-key $(accountKey)'
              visibleAzLogin: false
  - stage: PublishStorybook
    displayName: Publish to storybook
    dependsOn: SetVariables
    condition: and(eq(variables['Build.SourceBranch'], 'refs/heads/main'), succeeded())
    pool:
      vmImage: ubuntu-latest
    jobs:
      - job: PublishToStorybook
        displayName: Publish to storybook 
        steps:
          - checkout: self
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                # Write your commands here
                corepack enable
                yarn set version berry
          - task: Yarn@3
            displayName: Install Packages
            inputs:
              projectDirectory: "$(Build.SourcesDirectory)"
              arguments: 'install --immutable'
          - task: Yarn@3
            displayName: Build for storybook
            inputs:
              projectDirectory: "$(Build.SourcesDirectory)"
              arguments: 'build'
          - task: AzureStaticWebApp@0
            displayName: Publish to static webapp
            condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
            inputs:
              workingDirectory: "$(Build.SourcesDirectory)"
              app_build_command: 'yarn build:storybook'
              output_location: '/storybook-static'
              skip_app_build: false
              is_static_export: true
              azure_static_web_apps_api_token: '$(appToken)'
