trigger:

- main
- feature/*

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: Infrastructure
      type: git
      name: Webs/Infrastructure

variables:
  - name: appToken
    value: $(token)
  - name: npmToken
    value: $(NPM_TOKEN)

stages:
  - stage: Deploy
    displayName: Deploy to static app
    jobs:
    - job: BuildAndDeploy
      displayName: Build and deploy to storybook
      steps:
      - checkout: self
      - checkout: Infrastructure
      - task: YarnInstaller@3
        displayName: Install Yarn 1.22
        inputs:
          versionSpec: '1.22'
      - task: Yarn@3
        displayName: Install Packages
        inputs:
          projectDirectory: "$(Build.SourcesDirectory)/ui"
          arguments: 'install'
      - task: Yarn@3
        displayName: Run test
        inputs:
          projectDirectory: "$(Build.SourcesDirectory)/ui"
          arguments: test

        
      - task: Bash@3
        displayName: Check package version
        inputs:
          filePath: "$(Build.SourcesDirectory)/Infrastructure/scripts/check-npm-version.sh"
          arguments: "@djeka07/ui"
          workingDirectory: "$(Build.SourcesDirectory)/ui"
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            # Write your commands here
            echo "variables: $(SHOULD_PUBLISH) $(IS_RC)"
      - task: Bash@3
        displayName: 'Publish package to NPM'
        condition: eq(variables['SHOULD_PUBLISH'], true)
        inputs:
          filePath: "$(Build.SourcesDirectory)/Infrastructure/scripts/publish.sh"
          arguments: "$(IS_RC) $(npmToken)"
          workingDirectory: "$(Build.SourcesDirectory)/ui"
      - task: Yarn@3
        displayName: Build for storybook
        condition: eq(variables['SHOULD_PUBLISH'], false)
        inputs:
          projectDirectory: "$(Build.SourcesDirectory)/ui"
          arguments: 'build'
      - task: AzureStaticWebApp@0
        condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
        inputs:
          workingDirectory: "$(Build.SourcesDirectory)/ui"
          app_build_command: 'yarn build:storybook'
          output_location: '/storybook-static'
          skip_app_build: false
          is_static_export: true
          azure_static_web_apps_api_token: '$(appToken)'
